eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://animal-hotel-service-registry:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411/
